name: Tests

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-22.04

    container:
      image: python:3.10

    services:
      mobilitydb:
        image: codewit/mobilitydb
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Setup dependencies
        run: |
          apt-get -qq update
          apt-get -yqq install libgeos-dev libproj-dev proj-data proj-bin libgdal-dev

          # Below instructions are temporary until ubuntu ships with proj-8.0.0 or above
          apt-get -yqq install cmake sqlite3
          START_DIR=$PWD
          curl -sSL https://download.osgeo.org/proj/proj-8.2.1.tar.gz | tar -xvz -C /tmp
          cd /tmp/proj-8.2.1
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cmake --build . --target install
          projsync --system-directory --list-files
          cd $START_DIR

          poetry install
          poetry install -E movingpandas

      - name: Test with pytest
        run: poetry run pytest
        env:
          MOBILITYDB_HOST: mobilitydb
          MOBILITYDB_PORT: ${{ job.services.mobilitydb.ports[5432] }}
