name: Tests

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: python

    services:
      mobilitydb:
        image: codewit/mobilitydb
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Poetry (preview version)
        uses: dschep/install-poetry-action@v1.2
        with:
          preview: true

      - name: Setup dependencies
        run: |
          apt-get -qq update
          apt-get -yqq install libgeos-dev libproj-dev proj-data proj-bin libgdal-dev
          poetry install
          poetry install -E movingpandas

      - name: Test with pytest
        run: poetry run pytest
        env:
          MOBILITYDB_HOST: mobilitydb
          MOBILITYDB_PORT: ${{ job.services.mobilitydb.ports[5432] }}
